Apply suggestions from code review
Co-authored-by: Kathy Pippert <84872299+PipKat@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -263,7 +263,8 @@ jobs:
 
       - name: "Display MAPDL Logs"
         if: always()
-        run: cat log.txt || echo "MAPDL log not found"
+        run: cat log.txt || echo "MAPDL log could not be found."
+
 
 
   build-test:
