avoiding failing if logs not found

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -249,9 +249,9 @@ jobs:
       - name: "Tar logs"
         if: always()
         run: |
-          cp -f doc/_build/latex/*.log ./logs-build-docs/
-          cp log.txt ./logs-build-docs/
-          tar cvzf ./logs-build-docs.tgz ./logs-build-docs
+          cp -f doc/_build/latex/*.log ./logs-build-docs/ || echo "Latex logs couldn't be found."
+          cp log.txt ./logs-build-docs/ || echo "MAPDL log could not be found."
+          tar cvzf ./logs-build-docs.tgz ./logs-build-docs 
 
       - name: "Upload logs to GitHub"
         if: always()
@@ -262,7 +262,7 @@ jobs:
 
       - name: "Display MAPDL Logs"
         if: always()
-        run: cat log.txt
+        run: cat log.txt || echo "MAPDL log not found"
 
 
   build-test:
